# list of application_ids and associated model_architectures

- application_id: 0
  model_architecture: bloom-176b
  model_size: bloom-176b-fp16
  #model_architecture: llama2-70b
  #model_size: llama2-70b-fp16
  allocator: noop
  scheduler: round_robin
  overheads: {}
  debug: ${debug}
  _target_: application.Application
  scaling_manager:
    scale_up_delay: 1.0           # 扩容启动延迟（秒）
    drain_check_interval: 1.0      # 排空检查间隔（秒）
    enable_autoscaling: ${autoscaling.enable}        # 是否启用自动扩缩容
    decision_interval: ${autoscaling.decision_interval}  # 决策间隔（秒）
